version: '3.8'

services:
  web:
    build: .
    container_name: web
    env_file:
      - ./app/.env
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app

    ports:
      - 5000:5000
    networks:
      - appnet
      - internet
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    networks:
      - internet
      - appnet
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simbir_go
    ports:
      - 5432:5432
    networks:
      - appnet


volumes:
  postgres_data:

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge

